from pydantic import BaseModel, Field


class DocumentStatusCount(BaseModel):
    pending: int = Field(default=0, min=0)
    ongoing: int = Field(default=0, min=0)
    completed: int = Field(default=0, min=0)
    failed: int = Field(default=0, min=0)
    rejected: int = Field(default=0, min=0)


class DocumentWeeklyCount(BaseModel):
    monday: int = Field(default=0, min=0)
    tuesday: int = Field(default=0, min=0)
    wednesday: int = Field(default=0, min=0)
    thursday: int = Field(default=0, min=0)
    friday: int = Field(default=0, min=0)
    saturday: int = Field(default=0, min=0)
    sunday: int = Field(default=0, min=0)


class DocumentTypeCount(BaseModel):
    contract: int = Field(default=0, min=0)
    non_disclosure_agreement: int = Field(default=0, min=0)
    service_agreement: int = Field(default=0, min=0)
    employment_contract: int = Field(default=0, min=0)
    lease_agreement: int = Field(default=0, min=0)
    partnership_agreement: int = Field(default=0, min=0)
    memorandum_of_agreement: int = Field(default=0, min=0)
    memorandum_of_understanding: int = Field(default=0, min=0)
    addendum_amendment: int = Field(default=0, min=0)
    franchise_agreement: int = Field(default=0, min=0)
    indemnity_agreement: int = Field(default=0, min=0)
    articles_of_incorporation: int = Field(default=0, min=0)
    bylaws: int = Field(default=0, min=0)
    board_resolution: int = Field(default=0, min=0)
    shareholder_agreement: int = Field(default=0, min=0)
    minutes_of_meeting: int = Field(default=0, min=0)
    secretary_certificate: int = Field(default=0, min=0)
    general_information_sheet: int = Field(default=0, min=0)
    complaint: int = Field(default=0, min=0)
    affidavit: int = Field(default=0, min=0)
    subpoena: int = Field(default=0, min=0)
    court_order: int = Field(default=0, min=0)
    judgment: int = Field(default=0, min=0)
    supreme_court_decision: int = Field(default=0, min=0)
    court_of_appeals_decision: int = Field(default=0, min=0)
    motion: int = Field(default=0, min=0)
    summons: int = Field(default=0, min=0)
    pleading: int = Field(default=0, min=0)
    brief_memorandum: int = Field(default=0, min=0)
    last_will_and_testament: int = Field(default=0, min=0)
    deed_of_sale: int = Field(default=0, min=0)
    power_of_attorney: int = Field(default=0, min=0)
    trust_deed: int = Field(default=0, min=0)
    birth_certificate: int = Field(default=0, min=0)
    marriage_contract: int = Field(default=0, min=0)
    deed_of_donation: int = Field(default=0, min=0)
    prenuptial_agreement: int = Field(default=0, min=0)
    permit: int = Field(default=0, min=0)
    license: int = Field(default=0, min=0)
    government_issued_id: int = Field(default=0, min=0)
    tax_declaration: int = Field(default=0, min=0)
    tax_clearance: int = Field(default=0, min=0)
    certificate_of_registration: int = Field(default=0, min=0)
    constitution: int = Field(default=0, min=0)
    republic_act: int = Field(default=0, min=0)
    revenue_regulation: int = Field(default=0, min=0)
    revenue_memorandum_circular: int = Field(default=0, min=0)
    executive_order: int = Field(default=0, min=0)
    municipal_ordinance: int = Field(default=0, min=0)
    promissory_note: int = Field(default=0, min=0)
    deed_of_mortgage: int = Field(default=0, min=0)
    loan_agreement: int = Field(default=0, min=0)
    invoice: int = Field(default=0, min=0)
    receipt: int = Field(default=0, min=0)
    audited_financial_statement: int = Field(default=0, min=0)
    patent: int = Field(default=0, min=0)
    trademark_registration: int = Field(default=0, min=0)
    copyright_registration: int = Field(default=0, min=0)
    ip_assignment: int = Field(default=0, min=0)
    certification: int = Field(default=0, min=0)
    waiver: int = Field(default=0, min=0)
    notice: int = Field(default=0, min=0)
    other: int = Field(default=0, min=0)


class AdminDashboardData(BaseModel):
    active_user_count: int = Field(default=0, min=0)
    documents_count: int = Field(default=0, min=0)
    document_status_count: DocumentStatusCount = Field(default=None)
    document_weekly_count: DocumentWeeklyCount = Field(default=None)
    document_type_count: DocumentTypeCount = Field(default=None)
    chunks_count: int = Field(default=0, min=0)

    model_config = {"arbitrary_types_allowed": True}


class UserRegistrationMonthlyCount(BaseModel):
    january: int = Field(default=0, min=0)
    february: int = Field(default=0, min=0)
    march: int = Field(default=0, min=0)
    april: int = Field(default=0, min=0)
    may: int = Field(default=0, min=0)
    june: int = Field(default=0, min=0)
    july: int = Field(default=0, min=0)
    august: int = Field(default=0, min=0)
    september: int = Field(default=0, min=0)
    october: int = Field(default=0, min=0)
    november: int = Field(default=0, min=0)
    december: int = Field(default=0, min=0)
    
    
